language: ruby
os: linux
dist: bionic

services:
  - docker

script:
  - docker build -t $DOCKER_REPO .
  - docker tag $DOCKER_REPO $DOCKER_USERNAME/$DOCKER_REPO

deploy:
  provider: script
  script: docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD" && docker push $DOCKER_USERNAME/$DOCKER_REPO
  on:
    branch: master
    condition: $TRAVIS_EVENT_TYPE =~ ^(push|cron)$
